Use universal_io for web abstraction
flutterchina/cookie_jar pull request #36
Opened 2023-03-26 13:55 UTC by provokateurin

Follow up on https://github.com/flutterchina/cookie_jar/pull/35, since using universal_io is a lot easier and makes tests actually work. Some tests are still only for vm, since they save the cookies to disk (which is automatically handled by browser on web).

2023-03-28 07:24 UTC, AlexV525 commented
Since the plugin supports Dart from 2.12.0, adding the `universal_io` dependency will raise the constraint to 2.15.0. This is unexpected for us and we should discuss if this is necessary. Splitting tests is a good change though.

2023-04-03 17:59 UTC, AlexV525 commented
So what is your next planning move? Shall the PR continue? @provokateurin

2023-04-03 19:31 UTC, provokateurin commented
Yes, I don't see a reason why not. Having this working would help my lib support web too, so I'd really appreciate it

2023-04-03 19:33 UTC, provokateurin commented
I see your concern about raising the minimum dart version, but dart 2.15.0 has been out for a while and I think it's ok to move over (especially because there aren't huge changes between the versions like the nullabilty introduced with dart 2.12.0)

2023-04-07 09:27 UTC, provokateurin commented
@AlexV525 What do you think about my points? Can we move forward with this PR?

2023-04-28 10:15 UTC, AlexV525 requested changes

2023-04-28 10:15 UTC, AlexV525 commented on lib/src/cookie_jar.dart
> -    }
These should remain the same.

2023-04-28 10:15 UTC, AlexV525 commented on lib/src/file_storage.dart
> +import 'package:universal_io/io.dart' show File, Directory;
```suggestion
import 'package:universal_io/io.dart' show Directory, File;
```

2023-04-28 10:15 UTC, AlexV525 commented on test/cookie_jar_test.dart
> -import 'dart:typed_data';
We don't need to update tests IMO.

2023-04-28 14:51 UTC, AlexV525 commented on lib/src/cookie_jar.dart
> -    }
A convenient but wrong usage should not be preferred as always. If the entry is not stricted, users will have confusions since we didn't raise any warning, they might think the plugin will work as expected on Web.

2023-04-28 14:53 UTC, provokateurin commented on lib/src/cookie_jar.dart
> -    }
Hm but what is "will work as expected on Web". The plugin works, it's just doing nothing since the browser is handling everything.

2023-04-29 02:27 UTC, AlexV525 commented on lib/src/cookie_jar.dart
> -    }
> Hm but what is "will work as expected on Web"

It means managing cookies from the plugin.

2023-04-29 06:19 UTC, provokateurin commented on lib/src/cookie_jar.dart
> -    }
It was more of a philosophical question, but I'll just go with your approach. No need to discuss this anymore :)

2023-04-29 07:22 UTC, AlexV525 approved these changes
LGTM. Thanks for the change.

2023-04-29 07:56 UTC, merged